name: Deploy to Dev

on:
  pull_request:
    branches:
      - main
jobs:
  test_group1:
    name: Testing containers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose python3
          sudo apt-get install python3-pip
          sudo apt-get install python3-psycopg2
          sudo apt-get install python3-pytest